export const ESCROW_RELEASE_DELAY_DAYS = 7;
export const TRANSFER_PROCESSING_LEASE_MINUTES = 15;
export const MINUTES_IN_MILLISECONDS = 60 * 1000;
export const DAYS_IN_MILLISECONDS = 24 * 60 * MINUTES_IN_MILLISECONDS;
export const DISPUTE_OPENED_ERROR = 'DISPUTE_OPENED';
